158 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/testsuite b/testsuite
--- a/testsuite
+++ b/testsuite
@@ -18,11 +18,6 @@
 
 set -e
 
-if [ "$(id -u)" != 0 ]; then
-    echo "Error: this test suite needs to be run as root" >&2
-    exit 1
-fi
-
 # default config
 TESTSDIR="$(dirname $0)/t"
 : ${PG_UMASKS="022 077"}
@@ -31,22 +26,31 @@ help ()
 {
     echo "postgresql-common testsuite"
     echo "Syntax: $0 [options] [test ...]"
+    echo "    -f number        run tests starting at this number"
     echo "    -i               install packages for versions specified by -v"
+    echo "    -s               start a shell in the testbed on failure"
     echo "    -u 'umask ...'   umasks to run testsuite with [default: 022 077]"
     echo "    -v 'version ...' PostgreSQL versions to test [default: client versions installed]"
     exit ${1:-0}
 }
 
 # option parsing
-while getopts "hiu:v:" opt ; do
+while getopts "hf:isu:v:" opt ; do
     case $opt in
+        f) FROM="$OPTARG" ;;
         i) INSTALL=1 ;;
         h) help ;;
+        s) RUN_SHELL=1 ;;
         u) PG_UMASKS="$OPTARG" ;;
         v) export PG_VERSIONS="$OPTARG" ;; # used in t/TestLib.pm
         *) help 1 ;;
     esac
 done
+
+if [ "$(id -u)" != 0 ]; then
+    echo "Error: this test suite needs to be run as root" >&2
+    exit 1
+fi
 
 # install packages for versions specified by -v
 # needs network for apt, so run before unshare
@@ -66,6 +70,8 @@ if [ "${INSTALL:-}" ] && [ -z "${UNSHARED:-}" ]; then
         netcat-openbsd \
         hunspell-en-us
 fi
+# requirements on RedHat:
+# perl-Test-Simple perl-Time-HiRes
 
 # re-exec ourselves through unshare
 if [ -z "$UNSHARED" ]; then
@@ -89,7 +95,7 @@ if [ -e /etc/locale.gen ]; then
 	ru_RU.UTF-8 UTF-8
 EOF
     [ "$run" ] && locale-gen
-else
+elif [ -x /usr/sbin/locale-gen ]; then
     # Ubuntu
     # locale-gen will skip existing locales, so just call it for all here
     locale-gen en_US.UTF-8 ru_RU ru_RU.UTF-8
@@ -103,7 +109,7 @@ fi
 # let everything happen in overlay tmpfses to avoid interfering with already
 # existing clusters; this also speeds up testing
 mount --make-rprivate / 2> /dev/null || : # reset / to private mounts (systemd changes this to shared)
-dirs="/etc/postgresql /etc/postgresql-common /var/lib/postgresql /var/log/postgresql /var/run/postgresql"
+dirs="/etc/postgresql /etc/postgresql-common /var/lib/postgresql /var/log/postgresql /var/run/postgresql /dev/shm"
 created_dirs=""
 for d in $dirs; do
     if ! [ -d $d ]; then
@@ -124,6 +130,11 @@ chown root:postgres /var/log/postgresql
 chmod 1775 /var/log/postgresql
 chown postgres:postgres /var/run/postgresql
 chmod 2775 /var/run/postgresql
+chmod 1777 /dev/shm
+
+# the RPM packages enable the logging_collector by default, which the testsuite
+# doesn't like. We disable it unconditionally here.
+echo "logging_collector = off" >> /etc/postgresql-common/createcluster.conf
 
 # reset core limit for pg_ctl tests
 ulimit -S -c 0
@@ -156,7 +167,16 @@ for U in $PG_UMASKS; do
     echo "====== Running all tests with $TYPE umask $U ======="
     umask $U
     for T; do
-        echo "=== Running test `basename $T`... ==="
-        perl $T
+        TBASE=${T##*/}
+        [ "$FROM" ] && [ "${TBASE%%_*}" -lt "$FROM" ] && continue
+        echo "=== Running test $TBASE ... ==="
+        perl $T || {
+            EXIT=$?
+            if [ "${RUN_SHELL:-}" ]; then
+                echo "*** $TBASE failed with status $EXIT, dropping you into a shell in the testbed ***"
+                ${SHELL:-/bin/sh}
+            fi
+            exit $EXIT
+        }
     done
 done
