243 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/testsuite b/testsuite
--- a/testsuite
+++ b/testsuite
@@ -1,9 +1,9 @@
-#!/bin/sh
+#!/bin/bash
 
 # Run integration tests (on the installed packages).
 #
 # (C) 2005-2012 Martin Pitt <mpitt@debian.org>
-# (C) 2012-2021 Christoph Berg <myon@debian.org>
+# (C) 2012-2022 Christoph Berg <myon@debian.org>
 #
 #  This program is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
@@ -57,14 +57,11 @@ if [ "$(id -u)" != 0 ]; then
     exit 1
 fi
 
-# use the local pgcommon.sh (either in the build tree or /usr/share/postgresql-common)
-. ./pgcommon.sh
-get_release
-
 # install packages for versions specified by -v
 # needs network for apt, so run before unshare
 if [ "${INSTALL:-}" ] && [ -z "${UNSHARED:-}" ]; then
-    case $DISTRO in
+    . /etc/os-release
+    case $ID in
         debian|ubuntu)
             for v in $PG_VERSIONS; do
                 case $v in 8.*|9.*|10|11)
@@ -82,7 +79,6 @@ if [ "${INSTALL:-}" ] && [ -z "${UNSHARED:-}" ]; then
             apt-get install -y \
                 debhelper \
                 libecpg-dev \
-                locales \
                 procps systemd \
                 netcat-openbsd \
                 hunspell-en-us \
@@ -103,17 +99,15 @@ if [ "${INSTALL:-}" ] && [ -z "${UNSHARED:-}" ]; then
                 perl-Test-Simple perl-Time-HiRes \
                 gcc
         ;;
+        *)
+            echo "Unknown distribution ID $ID in /etc/os-release"
+            exit 1
+        ;;
     esac
 fi
 
 # shift away args
 shift $(($OPTIND - 1))
-
-# install locales
-locale_gen \
-    en_US.UTF-8 UTF-8 \
-    ru_RU ISO-8859-5 \
-    ru_RU.UTF-8 UTF-8
 
 # stop currently running clusters
 if [ -d /run/systemd/system ] ; then
@@ -200,14 +194,23 @@ for U in $PG_UMASKS; do
     for T; do
         TBASE=${T##*/}
         [ "${FROM:-}" ] && [ "${TBASE%%_*}" -lt "${FROM:-}" ] && continue
-        echo "=== Running test $TBASE ... ==="
+        echo "### PostgreSQL test $TBASE ###"
         perl -I. $T || {
             EXIT=$?
+            FAILED_TESTS="${FAILED_TESTS:-} $T"
             if [ "${FAILURE:-}" ]; then
                 echo "*** $TBASE failed with status $EXIT, dropping you into a shell in the testbed ***"
                 ${SHELL:-/bin/sh}
             fi
-            exit $EXIT
         }
+        echo "### End test $TBASE ###"
+        echo
     done
 done
+
+if [ "${FAILED_TESTS:-}" ]; then
+    echo "Failed tests: $FAILED_TESTS"
+    echo
+fi
+
+exit ${EXIT:-0}
